### ISSUE TITLE
SVN, and releases do not build with Mono 1.95 on OS X

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ardar/flowlib#10]
```
What steps will reproduce the problem?
1. Open Solution in Mono Develop
2. Build Solution
3. Build Fails.

What is the expected output? What do you see instead?

Build succeded, 0 errors, 0 warnings.

What version of the product are you using? ~~(Do not write latest)~~

20071222, 20080119, trunk

On what operating system?

Mac OS X

Call Stack? ~~(Line numbers and exception type helps much)~~

Performing main compilation...
Compilation failed: 2 error(s), 0 warnings

/Users/sreyan/Downloads/FlowLib20071222/Source/FlowLib/Utils/Compression/ZLibSub
Methods/DeflaterHuffman.cs(807,77):
error CS1002: Expecting `;'
/Users/sreyan/Downloads/FlowLib20071222/Source/FlowLib/Utils/Compression/ZLibSub
Methods/DeflaterHuffman.cs(814,27):
error CS1518: Expected `class', `delegate', `enum', `interface', or `struct'


Build complete -- 2 errors, 0 warnings
Please provide any additional information below.


```

Original issue reported on code.google.com by `sindhudw...@gmail.com` on 8 Apr 2008 at 3:14

**Comment by GoogleCodeExporter** [comment]
```
haha mono does a bad job at parsing that line.
replace :

if (storedOffset >= 0 && storedLength + 4 < opt_len >> 3) {

with:

if (storedOffset >= 0 && storedLength + 4 < (opt_len >> 3)) {

seems to fix the issue with 20071222
```

Original comment by `sindhudw...@gmail.com` on 8 Apr 2008 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
hmm...
operator precedece is the shit...
i have "fix" it. (svn 299)

if ((storedOffset >= 0) && ((storedLength + 4) < (opt_len >> 3))) {

have you reported this to mono develop?
If not. can you do this?
point them to this 
http://msdn2.microsoft.com/en-us/library/aa691323(VS.71).aspx :)


```

Original comment by `blomman84` on 8 Apr 2008 at 6:48
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Will do, thanks.
```

Original comment by `sindhudw...@gmail.com` on 29 Apr 2008 at 3:19
